# setuptools-scm doesn't work well with a shallow clone, see:
#    https://docs.gitlab.com/ee/ci/yaml/#shallow-cloning
variables:
  GIT_DEPTH: 0

.before_template: &before_defaults
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade setuptools wheel twine s3pypi "setuptools-scm[toml]" importlib_metadata

default:
  image:
    name: python:3.7-buster
    entrypoint: ["/bin/bash"]
  # Tags are not(!) inherited by jobs, contrary to the docs.
  # See: https://gitlab.com/gitlab-org/gitlab/issues/194312
  # tags:
  #   - kubernetes
  before_script:
    - *before_defaults


stages:
    - tools-bot
    - test
    - build
    - publish
    - verify
    - trigger


pytest:
  stage: test
  tags:
    - kubernetes
  before_script:
    - *before_defaults
    - pip install -e .[develop]
  script:
    - pytest -cov=hyp3lib
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'


build:
  stage: build
  tags:
    - kubernetes
  script:
    - echo "Building version $(python3 setup.py --version)"
    - python3 setup.py sdist bdist_wheel


deploy S3 PyPI:
  stage: publish
  tags:
    - kubernetes
  script:
    - echo "Uploading version $(python3 setup.py --version) to S3-PyPI"
    - s3pypi --bucket hyp3-pypi --verbose


test S3 PyPI:
  stage: verify
  tags:
    - kubernetes
  script:
    - python3 -m pip install hyp3lib --trusted-host "${S3_PYPI_HOST}" --extra-index-url "http://${S3_PYPI_HOST}"
