default:
  image: ubuntu:bionic
  # Tags are not(!) inherited by jobs, contrary to the docs.
  # See: https://gitlab.com/gitlab-org/gitlab/issues/194312
  # tags:
  #   - docker

stages:
    - tools-bot
    - build
    # - test
    - publish
    - verify
    - trigger

build:
  stage: build
  tags:
    - docker
  before_script:
    - python3 -m pip install --upgrade setuptools wheel twine s3pypi "setuptools-scm[toml]" importlib_metadata
  script:
    - echo "Building version $(python3 setup.py --version)"
    - python3 setup.py sdist bdist_wheel

deploy S3 PyPI:
  stage: publish
  tags:
    - docker
  before_script:
    - python3 -m pip install --upgrade setuptools wheel twine s3pypi "setuptools-scm[toml]" importlib_metadata
  script:
    - echo "Uploading version $(python3 setup.py --version) to S3-PyPI"
    - s3pypi --bucket hyp3-pypi --verbose

test S3 PyPI:
  stage: verify
  tags:
    - docker
  script:
    - python3 -m pip install hyp3lib --extra-index-url http://hyp3-pypi.s3-website-us-east-1.amazonaws.com
