# setuptools-scm doesn't work well with a shallow clone, see:
#    https://docs.gitlab.com/ee/ci/yaml/#shallow-cloning
variables:
  GIT_DEPTH: 0

default:
  image: ubuntu:bionic
  # Tags are not(!) inherited by jobs, contrary to the docs.
  # See: https://gitlab.com/gitlab-org/gitlab/issues/194312
  # tags:
  #   - docker
  before_script:
    - python3 -m pip install --upgrade setuptools wheel twine s3pypi "setuptools-scm[toml]" importlib_metadata


stages:
    - tools-bot
    - build
    # - test
    - publish
    - verify
    - trigger

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Building version $(python3 setup.py --version)"
    - python3 setup.py sdist bdist_wheel

deploy S3 PyPI:
  stage: publish
  tags:
    - docker
  script:
    - echo "Uploading version $(python3 setup.py --version) to S3-PyPI"
    - s3pypi --bucket hyp3-pypi --verbose

test S3 PyPI:
  stage: verify
  tags:
    - docker
  script:
    - python3 -m pip install hyp3lib --trusted-host "${S3_PYPI_HOST}" --extra-index-url "http://${S3_PYPI_HOST}"
