name: hyp3-lib
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  # For packaging, and testing
  - setuptools
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - boto3
  - gdal
  - imageio
  - importlib_metadata
  - lxml
  - matplotlib
  - netCDF4
  - numpy
  - pillow
  - pyproj>=2
  - pyshp
  - responses
  - requests
  - scipy
  - six
  - setuptools_scm
  - statsmodels
  - urllib3
  - pip:
    # for packaging and testing
    - s3pypi
    - safety

