# setuptools-scm doesn't work well with a shallow clone, see:
#    https://docs.gitlab.com/ee/ci/yaml/#shallow-cloning
variables:
  GIT_DEPTH: 0

default:
  image:
    name: continuumio/miniconda3:4.7.12
    entrypoint: ["/bin/bash"]

stages:
  - attempt
  - on-fail


ff merge:
  stage: attempt
  before_script:
    - chmod 600 ${GITLAB_TOOLS_BOT_SSH}
    - git config core.sshCommand "ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      -i ${GITLAB_TOOLS_BOT_SSH} -F /dev/null"
    - git config --global user.email "UAF-asf-apd@alaska.edu"
    - git config --global user.name "Tools-bot"
    - git remote set-url origin git@scm.asf.alaska.edu:hyp3/hyp3-ci.git
    - git fetch --all
  script:
    - git checkout develop && git pull --ff-only
    - git merge --ff-only origin/master
    - git push -o ci.skip


open merge-request:
  stage: on-fail
  before_script:
    - apt-get install -y jq curl
  script:
    - source .gitlab/merge_back.sh
  when: on_failure
