name: Tag New Version

on:
  push:
    branches:
      - main

jobs:
  call-bump-version-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.12.0
    with:
      user: tools-bot
      email: UAF-asf-apd@alaska.edu
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
