name: Test and Tag

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          activate-environment: hyp3-lib
          environment-file: environment.yml

      - name: Pytest in conda environment
        shell: bash -l {0}
        run: |
          python -m pip install .[develop]
          pytest --cov=hyp3lib

  tag:
    runs-on: ubuntu-latest
    needs: pytest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOOLS_BOT_PAK }}

      - name: Get associated PR
        uses: helaili/github-graphql-action@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
        with:
          query: .github/queries/associated-pr.query.yml
          outputFile: pr.json
          owner: ${{ github.repository_owner }}
          name: ${{ github.event.repository.name }}
          sha: ${{ github.sha }}

      - name: Get PR labels
        uses: helaili/github-graphql-action@2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
        with:
          query: .github/queries/pr-labels.query.yml
          outputFile: labels.json
          owner: ${{ github.repository_owner }}
          name: ${{ github.event.repository.name }}

      - uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Tag version
        uses: ASFHyP3/actions/bump-version@main
        with:
          user: tools-bot
          email: UAF-asf-apd@alaska.edu
